### ISSUE TITLE
[MembersJS] Update Signup/Signin + Stripe Checkout UI flow from Design Spec

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/members.js#10]
Part of TryGhost/Team#261 Epic

Work through the UI based on detailed design spec [here](https://github.com/TryGhost/Team/issues/261#issuecomment-611485911) for signup/signin/checkout flows

- [x] Add Signin Page
- [x] Add Signup page with plans list
- [x] Add Signed-in account page with subscription info
- [x] Handle state management for navigating between pages
- [x] Add page actions and hook them to API- `sendMagicLink`, `signout`, `checkoutPlan`
- [x] Visual Update based on https://sketch.cloud/s/PLaEx/a/dpre72/play
	- [x] Use Accent(brand) color of site for UI
- [x] Handle anonymous Stripe checkout session for allowing signup with a plan
  - [x] Pre-fill email address in stripe checkout session from signup area
  - [x] Link member to their checked out subscription
  - [x] Show success message from stripe url param on checkout complete

**Comment by rishabhgrg** [comment]
@peterzimon Have pushed all of the phase 2 UI flows with proper pages and state management structure etc, with one major change wrt how plan selection flow works. There is a small concern there:

<img width="1217" alt="anonymous-checkout" src="https://user-images.githubusercontent.com/3461456/79253541-0069f580-7ea1-11ea-9279-78721c58d891.png">

As per the current spec, we want to allow member to choose a plan during signup process, proceed to Stripe checkout and then complete the process using the magic link. That seems to be a bit tricky to handle with current setup, as we normally allow plan checkout after member is logged in(like in Lyra) to associate member's identity with the Stripe checkout session so the subscription is auto-linked to them. 

It might be possible to work with an anonymous Stripe Checkout session for pre-login checkout flow, and then later associate the subscription to that member, but it'll need bit more research, and figure out a way to pre-fill the member email into the anonymous Stripe checkout session. 

I have added a checkout flow for logged-in member for now in the flow, was thinking of coming back to pre-login checkout flow in the end after finishing other bits, but lmk if you think its something that needs to be solved earlier :)

**Comment by peterzimon** [comment]
@rishabhgrg this flow is the most common that covers all the important use cases, so I'd say we def. want to support it. the current lyra flow is a little bit awkward and uncommon. I don't think it's a big difference if we do it now or later, but probably I would look into technical solution/directions to it sooner rather than later
/cc @ErisDS

**Comment by rishabhgrg** [comment]
@peterzimon Cool, I am thinking of looking into the technical direction for this after the data initialisation in that case and we can still iterate on the checkout flow from logged-in page maybe till then. Couple of product questions that I think might popup with the signup checkout flow which we can start thinking about -

1. With the pre-signin checkout flow, an already paying member will be able to  use their email id and buy a new subscription, as we won't know about their existing subscriptions till the last step where they use the magic link. I know this is partly a mistake on their part and they can reach out to us if that happens, but flagging in case we have already encountered this so far, or if its an edge case that we can ignore :)

2. This is relatively minor and might mostly just need a technical work-around, but we currently don't have setup to pre-fill member's email address in checkout flow without their identity. Just flagging this early in case its not possible or extra tricky to pre-fill the email with anonymous checkout, and member might have to type it again, but will check on it to be sure.

**Comment by rishabhgrg** [comment]
Realized another limitation we have currently in signup flow is saving member's name during signup process. This is an issue because the magic-link creation flow in Core/Members is currently setup to only allow member's email and labels, and when a member uses magic link to signup we can only store those values in db.

This limitation can be easily resolved by extending the magic-link flow in Core/Members to allow storing `Name` as well, the only downside being that can increase the length of magic link compared to what we currently have. Not sure how much of an issue that is right now, but afair originally we didn't want to increase magic link length too much because of how they are visible in plain text emails. 🤔 

cc/ @peterzimon @ErisDS

**Comment by ErisDS** [comment]
@rishabhgrg please add this to the magic link for now, the magic link length issue is being tracked internally for a review and fix later. We can live with it for the time being.

**Comment by rishabhgrg** [comment]
Moved magic link fix in a new issue [here](https://github.com/TryGhost/members.js/issues/26), closing this as main UI changes for signup/signin flow from spec are now done.
