### ISSUE TITLE
Menu should close when clicking on the page "background"

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/members.js#15]
When logged in click on the floating button to open the logged in menu. ATM it's only possible to close the menu by clicking on the "X" icon. It should also be possible to close it via clicking away (i.e. anywhere outside the menu).

**Comment by rishabhgrg** [comment]
Closed in https://github.com/TryGhost/members.js/commit/94c052bf18f882d5fb0a0cd0776d251243f4bd86
