### ISSUE TITLE
[MembersJS] Add members API/SSR handling util

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/members.js#2]
Part of TryGhost/Team#261 Epic

Members sigin/signup/signout/checkout actions need API calls to members admin-api/ssr endpoints. Adds a small util that wraps all such external requests for use in CRA UI based on user action -

- [x] Sigin/Signup/Subscribe - Use `/members/send-magic-link/` admin API to send magic link to member's email
- [x] Signout - Use `members/ssr` endpoint to delete member's session
- [x] Checkout Plan - Use `members/ssr` endpoint to get signed-in member's identity and initiate a stripe checkout session
- [ ] Update lib structure

**Comment by rishabhgrg** [comment]
@ErisDS Have added the small api util [here](https://github.com/TryGhost/membersjs/blob/8f98a2d714d9e1dd0f6ff3576f570e368a046ae0/src/utils/api.js) which takes care of member requests for session management and api calls. 

Haven't extracted out a separate method for making API call as it seemed pretty straightforward with `fetch` here, but lmk if you think we should still add one.

Also the main thing here is we need values for `adminUrl` and `blogUrl` too setup API calls, which we are currently passing down hardcoded from theme during data initialization [here](https://github.com/rishabhgrg/Lyra/blob/4764651a884999af01bfee3e60c9dc26df3e25d7/default.hbs#L154-L155), which probably will need a better way to be passed down or read in theme as well.

**Comment by ErisDS** [comment]
This is covered by https://github.com/TryGhost/membersjs/issues/6#issuecomment-611506544

**Comment by rishabhgrg** [comment]
Closed in favor of https://github.com/TryGhost/members.js/issues/6
