### ISSUE TITLE
[MembersJS] Email is not pre-fill in Stripe checkout form

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/members.js#22]
When signing for a paid account ATM users have to enter their email twice: first in Ghost signup form and second in the Stripe checkout form. This is not optimal so if possible we should pre-fill the Stripe checkout form with the email that's provided by the user in the previous step.

**Comment by rishabhgrg** [comment]
Closed in https://github.com/TryGhost/members.js/commit/0a746a876468dd80ec9cca32ae8758865d641bc0
