### ISSUE TITLE
[MembersJS] Handle data initialization for CRA script

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/members.js#6]
Part of TryGhost/Team#261 Epic

The members.js script needs several data points about logged-in member as well as site. This data is currently present in theme through various handlebar helpers -

- `@member`: Contains signed-in member's information including `email`/`isPaid` 
- `@site`: Contains site info including title/description/logo 
- `@price`: Contains info about `monthly` and `yearly` plans which member can subscribe to

Members.js needs access to some or all of these data to manage UI state and interaction. Goal for this is to be able to initialize members.js script with this data when loaded in a theme.

- [x] Create spec for data need and flow in script
- [x] Use data through APIs instead of theme
  - [x] Site Data - `api/canary/admin/site`
  - [x] Is Member Logged in - Use members SSR identity
  - [x] Fetch member info from identity
- [x] Cleanup members API setup
  - [x] Use admin api url same as other SDKs (From integration page)
  - [x] Refactor api util similar to SDK code
- [x] Update `siteUrl` logic to use public site data instead of `window.location.origin`

**Comment by rishabhgrg** [comment]
@ErisDS Will be interested in hearing your thoughts on the approach in how we can pass or use member/site data inside the CRA script during initialization. 

Context: Members.js script needs info about member's logged-in state as well as their info if logged-in like email or plan they are subscribed to etc. to render different flows. Similarly it also needs access to basic site data like title/description/logo/admin-url etc. for showing relevant information in the popup flows. 

Currently, all of this data is available in theme through above handlebar helpers   which are used to render current member flows in theme. Currently the easiest way I found to pass these down to CRA script is directly via an  exposed init method which is called with relevant data through these helpers, after which script takes over in rendering UI flows. 

This is what I have pushed up [here](https://github.com/rishabhgrg/Lyra/commit/4764651a884999af01bfee3e60c9dc26df3e25d7) as example with Lyra theme of that works. The init method in MembersJS is [here](https://github.com/TryGhost/membersjs/blob/master/src/index.js#L19-L21)

Pros: 

- Pretty straightforward to pass all available info to script from theme via single init point.

Cons:
- As we ideally want to insert a single script tag with members.js src, this adds a bit of extra code that needs to be added by theme developer as part of using members.js. 
- Exposes an `init` method on window for members.js script like [here](https://github.com/TryGhost/membersjs/blob/master/src/index.js#L19-L21). Couldn't find an easier way so far to pass the data directly from theme without the need for exposing this. Will also need to figure out naming and namespace for this on `window` if we go ahead with this approach.

**Comment by rishabhgrg** [comment]
An alternate approach that came to mind is if we are serving the final bundled script from Ghost core through something like `ghost_head`, we could append the initialization step directly in there with relevant data so the theme developer will have to not copy paste the extra initialization step directly in theme but is already served with it.

Its kind of similar to what we do with `adminUrl` and `blogUrl` values in old members.js script, but something I am thinking of experimenting with. Lmk what you think :)

**Comment by ErisDS** [comment]
Big answer...

**Theoretical Solution:**

From an architectural perspective we want this script to be self-contained. We need to be thinking of this script as an independent API client, separate to the theme. The fact that it's dropped into a theme is an aside of how it's used, not part of how it functions.

Therefore we should not expect to rely on theme helpers to initialise the script, but rather be using API calls. The one piece of data that I imagine may need to be included unless we can come up with a smart solution, is the admin API URL, as it is not the same as window.location and cannot currently be guessed or determined.

**Real solution (available right now)**

The URL + title can be obtained from `api/canary/admin/site` - this endpoint is unauthenticated and designed for fetching public information needed to initialise admin clients. It totally makes sense that this would also expose description, icon & logo information, we just haven't had that use case before. Also the concept of this "open" endpoint was meant to live on the content API too, and it would make sense for it to also live on the members API.

That would solve part, but not all of the problem, but should at least be useful from the perspective of figuring out the necessary structure for the members.js script.

**Missing Stuff**

`@members` represents the members own data, I'd expect us to be able to retrieve this from the members API using their session.

`@price` is plan information, but I'm not clear on whether this is site or user specific and I'm fairly certain there must be both concepts. For an unauthenticated user there needs to be a list of plans they can subscribe to, and for an authenticated user there should be their own plan and any plans they can change to... 

It seems to me all of this should be coming from the members API but is currently unimplemented / missing.

**How to move forward**

Therefore I think it's OK to keep using the theme initialisation for the short term, but we need to clearly capture and document exactly what properties are needed along with when they are needed (i.e. on init, or on some other event) and why it is needed. @rishabhgrg please can you start capturing this spec? 

I'll use it to try to figure out what endpoints are missing and their ideal structure and write these up as separate issues.

**Comment by rishabhgrg** [comment]
@ErisDS All of above makes sense, I have started capturing the spec of everything that is or will be needed and at which point of flow 👍 

>  I'd expect us to be able to retrieve this from the members API using their session.

The whole SSR setup already includes member identity which we use during the stripe checkout flow, think that could be extended to cover this case as well, will take a quick look at it after spec.

**Comment by rishabhgrg** [comment]
@ErisDS 

### On script initialization

When the script is first loaded into theme, we'll need access to this data to trigger rest of the flow:

- Data
  - Site
    - title, description, logo: Used to add site information to the UI to make the flow look part of existing site instead of generic
    - membership plans: Used to show list of plans with prices that a new member can subscribe to or an existing member can switch to
    - allowed membership type - Free Only / Paid Only / Free + Paid : Used to configure the allowed plan flows for existing/new member
  - Member
    - isLoggedIn: Used to determine the first route/screen after initialization that user will see based on the member's logged in state

- Action APIs
  - None

### Signup/Signin Page

If member is not logged in:

- Data
  - Everything passed down from onInit

- Action APIs
  - Send magic link - Send magic link for signip/sigin
  - Trigger Stripe checkout with member identity - For paid plans stripe checkout flow

### Member signed-in

If member is logged in, their identity can be fetched with `/members/ssr` call and will be needed to fetch member's data:

- Data
  - Everything passed down from onInit
  - Member
    - name, email, gravatar(?) : Show member's profile info
    - subscription info: Show member's active plans and last 4 digits of card(maybe?) 
    - is newsletter enabled: Show if member's newsletter email is enabled

- Actions APIs
  - Edit Profile - Update member's profile info like name, email(?)
  - Edit Billing - Update member's card/plan info

**Comment by rishabhgrg** [comment]
@ErisDS Have pushed upstream(Commits Refs ^) v1 of Data initialization which takes care of fetching basic Site data and member's logged-in state through APIs directly and got rid of it being passed down from theme. The API and code re-structure is still WIP in how it will be eventually structured and used, but the logic/functionality works fine with the data from API.

- `GET /api/canary/admin/site/` : Extended this endpoint on core to add several new public settings like `logo`, `brand` and `description`, as well as using members service to pass info we can consider in public domain - `plans` and `allowSelfSignup`.

- `GET /members/ssr`: Uses member cookie to return logged-in member's identity if exists, `null` otherwise. Used in initialization to know current logged-in state of member.

Changes in core to extend site endpoint are on a branch [here](https://github.com/rishabhgrg/Ghost/tree/membersjs), have also removed most site info we pass down from theme(lyra) except the `adminUrl`.

**Comment by rishabhgrg** [comment]
@ErisDS Have extended data initialization to now take care of logged-in member's data through API as well, currently exposing the data through `<site>/members/ssr/member` endpoint where its fetched in exchange for member identity through `ghost-members-ssr` cookie. 

All changes are pushed upstream, and now the only dependency left on the theme for initialization is the `adminApi` url. Apart from figuring out how to solve for that, the next bits in data initialization that need focus imo are - 

- Site URL: Currently using `window.location.origin`, the `siteUrl` can be used from the public site settings we are fetching via Admin API.
- API Cleanup: Need to cleanup the members API structure in the script as we previously discussed to essentially be closer to members api sdk.
- Endpoint for fetching member data: Currently exposed via `/members/ssr/member` as an extension of current SSR endpoint, but needs more thought on if this is the right endpoint or needs change.

**Comment by ErisDS** [comment]
> Currently exposed via /members/ssr/member

Where is this code please?

**Comment by rishabhgrg** [comment]
@ErisDS Its pushed up [here](https://github.com/rishabhgrg/Ghost/commit/d58548d4a5840b15234cb75725a7bc0757913e3f), along with rest of core changes on a branch [here](https://github.com/rishabhgrg/Ghost/commits/membersjs)

**Comment by rishabhgrg** [comment]
Closed in https://github.com/TryGhost/members.js/commit/94c052bf18f882d5fb0a0cd0776d251243f4bd86
