### ISSUE TITLE
Various minor UI fixes

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/members.js#77]
There are a couple of minor UI fixes that should be done for Portal:

Admin:
- [x] add a close confirmation for Portal settings in the Admin if any properyt has been changed
- [x] first icon should be selected by default for Portal button

Frontend:
- [x] ~add currency value formatter (thousands indicator) to prices~
- [x] when chaning plan from the account page: for free members the first plan, for paid members the current plan should be selected by default
- [x] there's some weird flickering on the main button when logging in: (1) enabled "Send login link" -> (2) disabled "Sending" -> (3) enabled "Send login link" -> (4) check your inbox page. it should be (1) -> (2) -> (4)

Additions:
- [x] Account profile page: when clicking on "Save", the user should be redirected to the account home page (in case there's no error)
- [x] Account home page: since there are not much UI difference on Free vs. Paid, maybe a code cleanup could be done
- [x] Signup page + account plan page: discount value for yearly should only be displayed if monthly plan is turned on (otherwise it doesn't make sense)
- [x] (Subscribe) trigger button should always show the Subscribe screen. ATM if I go to the "sign in" screen, close it and click the trigger button again, I'm taken back to the "sign in" screen.
- [x] Admin Portal preview: there's a quick flicker before the portal popup appears. I wonder if we could elliminate this 😬

Additions part 2:
- [x] when changing plans on the frontend, members with complimentary plans should also have first available plan selected by default

**Comment by ErisDS** [comment]
> add currency value formatter (thousands indicator) to prices

IMO this should be consistent with the _planned_ changes to the theme helper? They haven't been confirmed, but this should be considered

**Comment by peterzimon** [comment]
@ErisDS @rishabhgrg - very good point, yes it should be consistent. so let's leave that one out for now (edited the original message)

**Comment by peterzimon** [comment]
@rishabhgrg @ErisDS @matthanley FYI: I added a couple of more items to the original list of todos. I thought it's better to collect them here since it's related and Rish haven't started it yet

**Comment by rishabhgrg** [comment]
End of week update:

The only thing that needs a final review in this issue before the merge on Monday is - 

>  Admin Portal preview: there's a quick flicker before the portal popup appears. I wonder if we could elliminate this 😬

Have added an approach to avoid flicker by hiding the iframe for a few seconds before showing, which allows portal to load, but want to review the behavior for this on Monday(or if a better approach clicks over weekend), and then this card should be ready to be moved to done. Time estimate - Max 0.5 day

**Comment by matthanley** [comment]
@rishabhgrg do you need any input from anyone else in order to progress this?

**Comment by rishabhgrg** [comment]
@matthanley No input needed from anyone, just wanted to self review all the final changes and reshuffle commits [here](https://github.com/TryGhost/Ghost-Admin/pull/1671) before merging this and moving to Done, which is all set now :)

**Comment by rishabhgrg** [comment]
Closed with merge of https://github.com/TryGhost/Ghost-Admin/pull/1671

@peterzimon Will be great if you can verify the fixes once you are back and if they need any design improvements :) Think the main task that will be cool to verify is 

> there's a quick flicker before the portal popup appears. I wonder if we could elliminate this 

The portal popup will always take a second or 2 to load once site frame is loaded as the script loads and does all the initialization, so the fix I did finally adds a consistent background overlay in preview and only shows the preview iframe after a second. As a result, the portal popup still appears after settings popup is opened, but its more consistent as background is always the same. Let me know if you have any other ideas :)

**Comment by peterzimon** [comment]
@rishabhgrg - I re-tested the listed issues and almost everything is fine. the only thing I found was that when changing plans on the frontend, members with complimentary plans should also have first available plan selected by default (similarly to free members)

**Comment by rishabhgrg** [comment]
Closed with https://github.com/TryGhost/members.js/commit/e6e7f036986d9a811e6d162f144a0013eccf83a4
