### ISSUE TITLE
Error handling for Portal frontend

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/members.js#78]
Error handling is missing for Portal frontend. There are two types of error messages in general: 

- local - attached to an input field (typically below it), copy is 
- global - appear somewhere in the popup

At the very minimum the following pages/screens and use cases should be handled.

### All the required input fields
- [x] Input values - if no value is provided to any input -> local error message (e.g. "Please supply an email")

### Signup
- [x] All input fields are required
- [x] Email format validation - for invalid email format -> local error message ("Invalid email address")

### Signin
- [x] All input fields are required
- [x] Email format validation - for invalid email format -> local error message ("Invalid email address")

### Account - Plan selection
- [x] If current plan is selected - click "continue" -> global error message ("Please select a different plan")

### Account - Profile
- [x] All input fields are required
- [x] Email format validation - for invalid email format -> local error message ("Invalid email address")

**Comment by peterzimon** [comment]
@rishabhgrg I'd like to ask one minor change regarding how error messages are displayed. currently if you do this:

1. click on "Subscribe"
2. focus on "Name" field
3. focus on "Email" field without entering a name

-> we show a dedicated error for both "Name" and "Email" fields

ideally we should show the error only for the field that's been focused out without entering any value, not all fields.

**Comment by rishabhgrg** [comment]
This is not working as expected on latest master with https://github.com/TryGhost/members.js/commit/c56eccd9899fe9ef31aa38b6b75e955a84f66bf5.
