### ISSUE TITLE
Upload custom icon refinements

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/members.js#79]
The interaction for uploading a custom portal icon should follow existing image upload patterns in the Admin (e.g. featured image for posts, publication icon/logo etc.), which is the following:

<img width="872" alt="Screenshot 2020-07-29 at 13 47 56" src="https://user-images.githubusercontent.com/353959/88796786-87b64d00-d1a2-11ea-8be2-f06b85a71145.png">

**Comment by rishabhgrg** [comment]
@peterzimon The linked PR updates the custom icon flow to the desired spec, think it needs minor design updates to trash icon and spinner so leaving it open till you have a look and tweak anything if needed :)

**Comment by rishabhgrg** [comment]
Closed with https://github.com/TryGhost/Ghost-Admin/pull/1675
