### ISSUE TITLE
[MembersJS]Allow custom trigger button on theme

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/members.js#8]
Part of TryGhost/Team#261 Epic

By default, we have a floating button that appears on the site to trigger the UI.
Optionally, if a custom trigger is detected via something like `data-members-trigger-button` - that's used instead as default trigger.

**Comment by rishabhgrg** [comment]
First version:

In case of a custom trigger button, CRA doesn't render the default trigger button and attaches click event handling to the custom button to control the popup UI. It also adds new custom class `popup-open` and `popup-close` based on popup state to allow theme developers to handle button UI based on popup state.

This can be tested with Lyra by uncommenting the custom trigger button [here](https://github.com/rishabhgrg/Lyra/blob/387b2ee91b80b7b6c3aa045206504ba7329dd49a/default.hbs#L47-L74), in which case CRA uses the custom trigger button for popup UI.

**Comment by rishabhgrg** [comment]
@peterzimon @ErisDS The main things that needs review here is

- Data attribute naming to mark the custom trigger button

Currently we use `data-members-trigger-button` to check and use a custom trigger button set by theme dev

- Updating custom trigger button based on popup state

We currently add `popup-open` and `popup-close` css classes to this custom button based on popup's state on interaction, to allow devs to control its UI based on if popup is open or closed. Does this pattern work, in which case we can figure out the naming, or should we look at something different to allow dev to control UI based on popup state ?

Custom trigger setup in members.js is [here](https://github.com/TryGhost/members.js/blob/1c8fde65d4acb92b37178f8e3babd18c2daa5392/src/components/ParentContainer.js#L20-L21) and in Lyra [here](https://github.com/rishabhgrg/Lyra/blob/387b2ee91b80b7b6c3aa045206504ba7329dd49a/default.hbs#L47-L74)

**Comment by peterzimon** [comment]
@rishabhgrg the behavior is great, there was one minor thing: the popup class didn't change back to `popup-close` when I closed the modal.

about naming: `data-members-trigger-button` is 👌 but for the classes let's add the namespace + BEM so: `gh-members-popup-open` and `gh-members-popup-close`

other than this, it works great! thanks

**Comment by rishabhgrg** [comment]
@peterzimon ^ Above behavior was added in https://github.com/TryGhost/members.js/commit/a9fe93b663a92522b10e598dbfb15f5ec3a316c3

**Comment by rishabhgrg** [comment]
Closed with https://github.com/TryGhost/members.js/commit/a9fe93b663a92522b10e598dbfb15f5ec3a316c3
