### ISSUE TITLE
Various Portal refinements

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/members.js#95]
Hey @rishabhgrg, below are a couple of Portal bugs and refinements I need your help with:

- [x] Account home: when toggling the newsletter switch, we should show a temporarily text ("✔️ Updated") to show that the setting has been saved
- [x] Accout plan: members with complimentary plans should have a static text indication that they are on complimentary plan (copy to be refined)
- [x] Whole frontend: hitting ESC should close the modal
- [x] Account plan for free users: If there's only one paid plan turned on, then 
    - for free members: "Subscribe" button should open Stripe right on (skip plan selection)
    - for paid members: open plan selection as usual (cancel/continue will be there too so we need this page anyways)

**Comment by rishabhgrg** [comment]
Closed in favor of https://github.com/TryGhost/Team/issues/384 which has refined the plan update flow
